# BACKGROUND
background {
    monitor =
    path = ~/Pictures/Wallpapers/Zluk/cyberpunk-red-background-cyberpunk-girl-futuristic-5k-3840x2160-7630.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# GREETINGS
label {
    monitor =
    text = Welcome to Estudio
    color = rgba(0, 0, 0, 0.85)
    font_size = 55
    font_family = Tanker
    position = 135, 350
    halign = left
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(0, 0, 0, 0.85)
    font_size = 70
    font_family = Sentient Medium
    position = 290, 240
    halign = left
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(0, 0, 0, 0.85)
    font_size = 19
    font_family = Switzer semibold
    position = 310, 165
    halign = left
    valign = center
}

# PROFILE-PHOTO
image {
    monitor =
    path =
    border_size = 2
    border_color = rgba(0, 0, 0, 0.85)
    size = 95
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    position = 270, 25
    halign = left
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 330, 62
    color = rgba(0, 0, 0, 0.9)
    rounding = -1
    border_size = 0
    border_color = rgba(0, 0, 0, 1)
    rotate = 0
    xray = false

    position = 235, -110
    halign = left
    valign = center
}

# USER
label {
    monitor =
    text =   $USER
    color = rgba(221, 11, 39, 1.0)
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    font_size = 16
    font_family = JetBrains Mono Medium
    position = 355, -110
    halign = left
    valign = center
}

# INPUT FIELD (PASSWORD BOX → BLACK SHADE)
input-field {
    monitor =
    size = 316, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 1.0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(0, 0, 0, 1.0)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <span foreground="##00000099">Password</span>
    hide_input = false
    position = 242, -215
    halign = left
    valign = center
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)"
    color = rgba(0, 0, 0, 0.75)
    font_size = 14
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 250, 45
    halign = left
    valign = bottom
}

# Power off
label {
    text = 󰐥
    font_family = JetBrainsMono Nerd Font Mono
    color = rgba(0, 0, 0, 0.9)
    font_size = 45
    onclick = systemctl poweroff

    position = 260, 100
    halign = left
    valign = bottom
}

# Reboot
label {
    text = 󰜉
    font_family = JetBrainsMono Nerd Font Mono
    color = rgba(0, 0, 0, 0.9)
    font_size = 45
    onclick = systemctl reboot

    position = 385, 100
    halign = left
    valign = bottom
}

# Suspend
label {
    text = 󰤄
    font_family = JetBrainsMono Nerd Font Mono
    color = rgba(0, 0, 0, 0.9)
    font_size = 40
    onclick = systemctl suspend

    position = 510, 100
    halign = left
    valign = bottom
}
